# List of street names in Venezuela
street_names = [
    "Calle Bolívar",
    "Avenida Urdaneta",
    "Carrera 19 de Abril",
    "Transversal Los Palos Grandes",
    "Calle 5 de Julio",
    "Avenida Andrés Bello",
    "Carrera El Rosal",
    "Calle Los Caobos",
    "Avenida Libertador",
    "Carrera Sabana Grande",
    "Calle La Candelaria",
    "Avenida Francisco de Miranda",
    "Carrera Los Dos Caminos",
    "Calle El Paraíso",
    "Avenida Rómulo Gallegos",
    "Carrera Altamira",
    "Transversal Las Mercedes",
    "Calle Los Chaguaramos",
    "Avenida Baralt",
    "Carrera La Florida",
    "Calle San Bernardino",
    "Avenida Boyacá",
    "Carrera Los Cortijos",
    "Transversal Santa Fe",
    "Calle Los Dos Caminos",
    "Avenida Sucre",
    "Carrera El Marqués",
    "Calle La Castellana",
    "Avenida Bolívar",
    "Carrera Los Ruices",
    "Transversal El Cafetal",
    "Calle El Hatillo",
    "Avenida Los Samanes",
    "Carrera La Trinidad",
    "Calle Los Palos Grandes",
    "Avenida Las Mercedes",
    "Carrera Bello Monte",
    "Transversal Los Dos Caminos",
    "Calle Los Cortijos",
    "Avenida Los Palos Grandes",
    "Carrera El Cafetal",
    "Calle Los Ruices",
    "Avenida El Marqués",
    "Carrera La Castellana",
    "Transversal La Florida",
    "Calle Los Samanes",
    "Avenida El Hatillo",
    "Carrera Los Palos Grandes",
    "Calle Bello Monte",
    "Avenida Los Cortijos",
    "Carrera Las Mercedes",
    "Transversal El Rosal",
    "Calle La Trinidad",
    "Avenida Los Dos Caminos",
    "Carrera Las Palmas",
    "Calle El Cafetal",
    "Avenida Los Ruices",
    "Carrera El Paraíso",
    "Transversal Los Caobos",
    "Calle Los Samanes",
    "Avenida La Candelaria",
    "Carrera El Hatillo",
    "Transversal Los Palos Grandes",
    "Calle Los Dos Caminos",
    "Avenida El Rosal",
    "Carrera Las Mercedes",
    "Transversal Los Ruices",
    "Calle El Marqués",
    "Avenida La Castellana",
    "Carrera Los Samanes"
]

# Write the street names to a text file
with open("venezuela_street_names.txt", "w") as file:
    for street in street_names:
        file.write(street + "\n")

print("Street names saved to venezuela_street_names.txt")
