# List of 70 food product names
food_products = [
    "Arroz",
    "Frijoles",
    "Harina de maíz",
    "Pasta",
    "Aceite de oliva",
    "Azúcar",
    "Sal",
    "Leche",
    "Huevos",
    "Pan",
    "Queso",
    "Jamón",
    "Atún",
    "Sardinas",
    "Pollo",
    "Carne de res",
    "Pavo",
    "Cerdo",
    "Ternera",
    "Salchichas",
    "Tofu",
    "Yogur",
    "Mantequilla",
    "Miel",
    "Café",
    "Té",
    "Cacao",
    "Chocolate",
    "Galletas",
    "Cereales",
    "Avena",
    "Frutas",
    "Verduras",
    "Tomates",
    "Papas",
    "Zanahorias",
    "Cebollas",
    "Ajo",
    "Pimientos",
    "Espinacas",
    "Brócoli",
    "Calabacín",
    "Pepinos",
    "Plátanos",
    "Manzanas",
    "Naranjas",
    "Uvas",
    "Fresas",
    "Piña",
    "Sandía",
    "Melón",
    "Mango",
    "Pera",
    "Kiwi",
    "Almendras",
    "Nueces",
    "Avellanas",
    "Cacahuetes",
    "Pistachos",
    "Sésamo",
    "Chía",
    "Lentejas",
    "Garbanzos",
    "Alubias",
    "Quinoa",
    "Cuscús",
    "Cebada",
    "Trigo",
    "Centeno",
    "Maíz",
    "Avena",
    "Arándanos",
    "Frambuesas",
    "Moras",
    "Cerezas",
    "Granada",
    "Higos",
    "Dátiles",
    "Pasas"
]

# Write the food product names to a text file
with open("productos.txt", "w") as file:
    for product in food_products:
        file.write(product + "\n")

print("The food product names have been saved to food_products.txt")
